name: "Setup Dify sevices"

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select an environment
        options:
          - staging
          - uat

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: langgenius/dify
          ref: refs/tags/1.0.0

      - name: Copy deploy folder to remote staging server
        uses: appleboy/scp-action@v0.1.7
        if: ${{ inputs.environment == 'staging' }}
        with:
          host: ${{ secrets.SSH_HOST_STAGING }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY_UATSTAGING }}
          source: services/quivr/supabase/*
          target: ./*
          strip_components: 2

    
