name: "Setup Dify sevices"

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select an environment
        options:
          - staging
          - uat

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        run: git clone https://github.com/langgenius/dify.git --branch 0.15.3
        
      - name: Copy deploy folder to remote staging server
        uses: appleboy/scp-action@v0.1.7
        if: ${{ inputs.environment == 'staging' }}
        with:
          host: 103.112.211.145
          username: root
          password: soE6n1pzLqNofO
          source: ./*
          target: /home/admin/app/uat
          strip_components: 2

    
